- name: Install Redis
  apt:
    name: redis-server
    state: present

- name: Configure Redis to bind to all interfaces
  lineinfile:
    path: /etc/redis/redis.conf
    regexp: '^bind'
    line: 'bind 0.0.0.0'
  register: redis_config_changed

- name: Restart Redis if config changed
  service:
    name: redis-server
    state: restarted
  when: redis_config_changed.changed

- name: Ensure Redis service is enabled and started
  service:
    name: redis-server
    enabled: yes
    state: started
