- name: Create the directory
  file:
    path: /opt/worker-app
    state: directory
    mode: 0755

- name: Download the Java JDK tar
  get_url:
    url: https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
    dest: /tmp/jdk-21_linux-x64_bin.deb

- name: Install Java JDK
  apt:
    deb: /tmp/jdk-21_linux-x64_bin.deb
    state: present

- name: Extract worker application
  unarchive:
    src: "{{ playbook_dir }}/worker.tar"
    dest: /opt/worker-app
    mode: '0755'
    remote_src: no

- name: Install Maven
  apt:
    name: maven
    state: present
    update_cache: no

- name: Find JDK installation directory
  shell: "find /usr/lib/jvm -maxdepth 1 -name 'jdk*' | head -n 1"
  register: jdk_dir
  changed_when: false

- name: Build Maven project
  shell: "JAVA_HOME={{ jdk_dir.stdout }} mvn -B clean package"
  args:
    chdir: /opt/worker-app
  when: jdk_dir.stdout != ""

- name: Create systemd service file for worker app
  template:
    src: files/worker.service
    dest: /etc/systemd/system/worker.service
    mode: '0644'
  register: worker_service_changed

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  when: worker_service_changed.changed

- name: Ensure worker service is enabled and started
  systemd:
    name: worker
    enabled: yes
    state: started