- name: Update apt cache with relaxed GPG checks
  shell: apt-get update -o Acquire::AllowInsecureRepositories=true -o Acquire::AllowDowngradeToInsecureRepositories=true
  changed_when: false
  ignore_errors: yes

- name: Install NTP for time synchronization
  apt:
    name: ntp
    state: present
    update_cache: no

- name: Set timezone to UTC
  timezone:
    name: UTC

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
    enabled: yes

- name: Install Git
  apt:
    name: git
    state: present
    update_cache: no
    allow_unauthenticated: yes

- name: Install Python and pip
  apt:
    state: present
    name:
      - python3
      - python3-pip
      - python3-setuptools
    allow_unauthenticated: yes

- name: Install curl and basic utilities
  apt:
    state: present
    name:
      - curl
      - ca-certificates
      - gnupg
    allow_unauthenticated: yes

- name: Install UFW
  apt:
    state: present
    name: ufw
    allow_unauthenticated: yes

- name: Allow SSH through firewall
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Allow HTTP through firewall
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Enable firewall
  ufw:
    state: enabled
    policy: deny